---
# tasks file for myvhost
# 1. 패키지 설치 
# 2. 서비스 기동 
# 3. 서비스 설정  
# 4. 방화벽 등록

# 1. 패키지 설치 - httpd, mod_ssl 
- name: 웹 패키지 설치 
  yum:
    name: 
      - httpd
      - mod_ssl
    state: latest

# 2. 서비스 기동 - httpd 
- name: 웹 서비스 기동 
  service:
    name: httpd
    state: started
    enabled: true

# 3. 서비스 설정 - /etc/httpd/conf.d/vhost.conf
- name: 웹 서비스 설정 
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: '0644'
  # changed_when: true 
  notify:
    - restart web 

# 4. 방화벽 등록 - http, https 
- name: 방화벽에 포트 등록 
  firewalld:
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  with_items: 
    - http 
    - https 
    
